[hostname]
ssh_only = false
# suffix = ""
disabled = false

[username]
show_always = true

[git_status]
conflicted = "=${count}"  # This branch has merge conflicts.
ahead      = "⇡${count}"
behind     = "⇣${count}"
diverged   = "⇕⇡${ahead_count}⇣${behind_count}"
untracked  = "?${count}"
stashed    = "$${count}"
modified   = "!${count}"
staged     = "+${count}"
renamed    = "»${count}"
deleted    = "✘${count}"

[directory]
truncate_to_repo = false

[rust]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[python]
disabled = true